ip_route : sudo mkdir /tmp/ip_route && netstat - rn > /tmp/ip_route
access_list : sudo /tmp/access_list && iptables -L -n > /tmp/access_list
licence: sudo mkdir /tmp/licence && cl-license > /tmp/licence