- "/mnt/disk/etc/hosts"
- "/mnt/disk/etc/network/interfaces"
- "/mnt/disk/etc/hosts"
- "/mnt/disk/etc/frr/daemons.conf"
- "/mnt/disk/etc/frr/daemons"
- "/mnt/disk/etc/resolv.conf"
- "/mnt/disk/etc/ntp.conf"
- "/mnt/disk/etc/snmp/snmpd.conf"
- "/mnt/disk/etc/motd"
- "/mnt/disk/etc/passwd"
- "/mnt/disk/etc/cumulus/switchd.conf"
- "/mnt/disk/etc/cumulus/ports.conf"
- "/mnt/disk/etc/cumulus/datapath/traffic.conf"
- "/mnt/disk/etc/cumulus/etc.replace/os-release"
- "/mnt/disk/etc/hostname"
- "/mnt/disk/etc/frr/frr.conf"