ip_route : sudo touch /tmp/ip_route && netstat - rn > /tmp/ip_route
access_list : sudo touch /tmp/access_list && iptables -L -n > /tmp/access_list
licence: sudo touch /tmp/licence && cl-license > /tmp/licence