---
path_vm_info: /Volumes/Data/gitlab/python-eveng-api/vm/vm_info.yml
devices:
  - labname: spine-leaf.unl
    hostname: Spine01
    config: ./config/oob/Spine01
  - labname: spine-leaf.unl
    hostname: Spine02
    config: ./config/oob/Spine02
  - labname: spine-leaf.unl
    hostname: Spine03
    config: ./config/oob/Spine03
  - labname: spine-leaf.unl
    hostname: Leaf01
    config: ./config/oob/Leaf01
  - labname: spine-leaf.unl
    hostname: Leaf02
    config: ./config/oob/Leaf02
  - labname: spine-leaf.unl
    hostname: Leaf03
    config: ./config/oob/Leaf03
  - labname: spine-leaf.unl
    hostname: Leaf04
    config: ./config/oob/Leaf04
  - labname: spine-leaf.unl
    hostname: Leaf05
    config: ./config/oob/Leaf05