- "/mnt/disk/etc/hostname"
- "/mnt/disk/etc/sudoers"
- "/mnt/disk/etc/resolv.conf"
- "/mnt/disk/etc/dnsmasq.conf"
- "/mnt/disk/etc/ntp.conf"
#- "/mnt/disk/etc/motd"
- "/mnt/disk/etc/passwd"
- "/mnt/disk/etc/hosts"
- "/mnt/disk/etc/ipsec.conf"
- "/mnt/disk/etc/rsyslog.conf"
- "/mnt/disk/etc/pptpd.conf"
- "/mnt/disk/etc/network/interfaces"
- "/mnt/disk/etc/quagga/bgpd.conf"
- "/mnt/disk/etc/quagga/ospf6d.conf"
- "/mnt/disk/etc/quagga/ripd.conf"
- "/mnt/disk/etc/quagga/vtysh.conf"
- "/mnt/disk/etc/quagga/isisd.conf"
- "/mnt/disk/etc/quagga/ospfd.conf"
- "/mnt/disk/etc/quagga/ripngd.conf"
- "/mnt/disk/etc/quagga/zebra.conf"
- "/mnt/disk/etc/snmp/snmpd.conf"
- "/mnt/disk/etc/ldap/ldap.conf"
- "/mnt/disk/etc/ssmtp/ssmtp.conf"
- "/mnt/disk/etc/ssmtp/revaliases"
- "/mnt/disk/etc/dhcp/dhclient-exit-hooks.d/ntp"
- "/mnt/disk/etc/dhcp/dhclient-exit-hooks.d/ntpdate"
- "/mnt/disk/etc/dhcp3/dhclient.conf"
- "/mnt/disk/etc/dhcp3/dhcpd.conf"
- "/mnt/disk/etc/dhcp3/dhclient-exit-hooks.d/ipsecd"
- "/mnt/disk/etc/dhcp3/dhclient-exit-hooks.d/l2tpd"
- "/mnt/disk/etc/dhcp3/dhclient-exit-hooks.d/pptpd"
