- "/mnt/disk/etc/network/interfaces"
- "/mnt/disk/etc/quagga/bgpd.conf"
- "/mnt/disk/etc/quagga/ospf6d.conf"
- "/mnt/disk/etc/quagga/ripd.conf"
- "/mnt/disk/etc/quagga/vtysh.conf"
- "/mnt/disk/etc/quagga/isisd.conf"
- "/mnt/disk/etc/quagga/ospfd.conf"
- "/mnt/disk/etc/quagga/ripngd.conf"
- "/mnt/disk/etc/quagga/zebra.conf"